### ISSUE TITLE
Suddenly the aplication has stopped working

### ISSUE THREAD

**Issue by p1mpst4r** [vhsantos/centreon_report_to_pdf#11]
this is the output that the aplication trow back

[root@ssg-monitoring-01 centreon_report_to_pdf]# /opt/rh/rh-python36/root/usr/bin/python /root/centreon_report_to_pdf/centreon_report_to_pdf.py -c /root/centreon_report_to_pdf/config.ini > /root/centreon_report_to_pdf/job.log
Traceback (most recent call last):
  File "/root/centreon_report_to_pdf/centreon_report_to_pdf.py", line 10, in <module>
    get_command_line_args()
  File "/root/centreon_report_to_pdf/Settings.py", line 524, in get_command_line_args
    config.read(final_config_file)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2055: invalid start byte

**Comment by vhsantos** [comment]
Hi,

That is because you have some strange character (no UTF-8) on your configuration file. Check it.

**Comment by p1mpst4r** [comment]
Hello Victor, yes i spent a lot time figuring what was wrong and in the end i found that my config.ini was not UTF-8 (i had edited it outside the machine and then uploaded it).
just a easy file -i command sort out the problem (me dumb... where bananas ?).
Thank you very much for the your reply.

Blessing from italy
